import { resume, resumeEnglish } from './resumeData'

const Arrow = () => <span aria-hidden="true">↗</span>
function handleContactSubmit(event, language) {
  event.preventDefault()
  const formData = new FormData(event.currentTarget)
  const data = getContent(language)
  const subject = language === 'en' ? `Contact from ${formData.get('name')}` : `Contato de ${formData.get('name')}`
  const body = `${language === 'en' ? 'Name' : 'Nome'}: ${formData.get('name')}\n${language === 'en' ? 'Email' : 'E-mail'}: ${formData.get('email')}\n\n${formData.get('message')}`
  window.location.href = `mailto:${data.email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
}
const labels = {
  pt: { about: 'Sobre Mim', projects: 'Projetos', experience: 'Experiência', contact: 'Contato', quick: 'Links Rápidos', social: 'Social', portfolio: 'Portfólio', rights: 'Todos os direitos reservados.', hello: 'Olá, eu sou', developer: 'Desenvolvedor de Software', seeProjects: 'Ver Projetos', profile: 'Perfil profissional', objective: 'Objetivo profissional', education: 'Formação Acadêmica', area: 'Área de Atuação', interests: 'Principais Interesses', skills: 'Habilidades', specific: 'Conhecimentos específicos', projectsTitle: 'Meus Projetos', projectsDesc: 'Conheça projetos desenvolvidos ao longo da minha formação e experiência profissional.', project: 'Projeto', view: 'Ver Projeto', github: 'GitHub', history: 'Histórico profissional', experienceDesc: 'Minha trajetória profissional e as principais atividades desenvolvidas em cada posição.', exp: 'Experiência', academic: 'Formação acadêmica', contactDesc: 'Entre em contato para conversarmos sobre oportunidades, projetos e tecnologia.', contactInfo: 'Informações de Contato', message: 'Envie uma mensagem', required: '(Obrigatório)', name: 'Nome', email: 'E-mail', phone: 'Telefone', messageField: 'Mensagem', send: 'Enviar', age: 'anos', semester: 'período', license: 'CNH' },
  en: { about: 'About Me', projects: 'Projects', experience: 'Experience', contact: 'Contact', quick: 'Quick Links', social: 'Social', portfolio: 'Portfolio', rights: 'All rights reserved.', hello: 'Hello, I am', developer: 'Software Developer', seeProjects: 'View Projects', profile: 'Professional profile', objective: 'Professional objective', education: 'Education', area: 'Area of expertise', interests: 'Main interests', skills: 'Skills', specific: 'Technical skills', projectsTitle: 'My Projects', projectsDesc: 'Explore projects developed throughout my education and professional experience.', project: 'Project', view: 'View Project', github: 'GitHub', history: 'Professional experience', experienceDesc: 'My professional journey and the main activities developed in each position.', exp: 'Experience', academic: 'Academic background', contactDesc: 'Get in touch to discuss opportunities, projects and technology.', contactInfo: 'Contact information', message: 'Send a message', required: '(Required)', name: 'Name', email: 'Email', phone: 'Phone', messageField: 'Message', send: 'Send', age: 'years old', semester: 'semester', license: 'license' },
}
const getContent = (language) => language === 'en' ? resumeEnglish : resume
const Shell = ({ eyebrow, title, description, children }) => <section className="mx-auto max-w-[1020px] px-6 pb-20 pt-12 lg:px-10 lg:pt-16"><p className="text-xs font-bold uppercase tracking-wide text-[#777]">{eyebrow}</p><h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1>{description && <p className="mt-3 max-w-2xl text-sm leading-relaxed text-[#666]">{description}</p>}{children}</section>
const Footer = ({ language }) => { const t = labels[language]; const data = getContent(language); return <footer className="border-t border-[#eee] bg-[#fafafa] px-6 py-10 text-xs text-[#777]"><div className="mx-auto grid max-w-[1020px] gap-8 sm:grid-cols-3"><div><strong className="text-sm text-[#222]">{t.portfolio}</strong><p className="mt-3 leading-relaxed">{data.name}</p></div><div><strong className="text-sm text-[#222]">{t.quick}</strong><div className="mt-3 grid gap-2"><a href="/about">{t.about}</a><a href="/projects">{t.projects}</a><a href="/experience">{t.experience}</a><a href="/contact">{t.contact}</a></div></div><div><strong className="text-sm text-[#222]">{t.social}</strong><div className="mt-3 flex gap-4 text-base"><a href={data.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn">in</a><a href={`mailto:${data.email}`} aria-label={t.email}>✉</a></div></div></div><div className="mx-auto mt-10 max-w-[1020px] border-t border-[#e5e5e5] pt-5 text-[10px]">© 2026 {data.name}. {t.rights}</div></footer> }

export function HomePage({ language, navigate }) { const t = labels[language]; const data = getContent(language); return <><section className="mx-auto grid max-w-[1020px] items-center gap-10 px-6 py-14 lg:grid-cols-[1fr_300px] lg:px-10 lg:py-16"><div><p className="mb-5 text-xs font-bold uppercase tracking-wide text-[#777]">{t.hello}</p><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{data.name}</h1><p className="mt-2 text-base italic text-[#777]">{data.title}</p><p className="mt-6 max-w-lg text-sm leading-relaxed text-[#555]">{data.objective}</p><div className="mt-7 flex gap-3"><button onClick={() => navigate('projects')} className="bg-[#171717] px-5 py-3 text-xs font-semibold text-white">{t.seeProjects} <Arrow /></button><button onClick={() => navigate('contact')} className="border border-[#ddd] px-5 py-3 text-xs font-semibold">{t.contact}</button></div></div><div className="mx-auto aspect-square w-full max-w-[300px] overflow-hidden border border-dashed border-[#ccc] bg-[#f2f2f2]"><img src="/profile.png" alt={language === 'en' ? 'Gabriel Silva Neiva Amaro profile photo' : 'Foto de Gabriel Silva Neiva Amaro'} className="h-full w-full object-contain" /></div></section><section className="border-y border-[#eee]"><div className="mx-auto max-w-[1020px] px-6 py-12 lg:px-10"><h2 className="text-xl font-bold underline decoration-[#ddd] decoration-2 underline-offset-8">{t.about}</h2><p className="mt-6 max-w-2xl text-xs leading-relaxed text-[#555]">{data.summary}</p><div className="mt-8 grid gap-6 text-xs sm:grid-cols-2"><Info title={t.education} text={data.education[0][1]} /><Info title={t.area} text={language === 'en' ? 'Software development, automation and QA' : 'Desenvolvimento, automação e QA'} /><Info title={t.interests} text={language === 'en' ? 'Technology and software development' : 'Tecnologia e desenvolvimento de software'} /><Info title={t.objective} text={data.objective} /></div><h2 className="mt-12 text-xl font-bold">{t.skills}</h2><SkillGroups language={language} /></div></section><Footer language={language} /></> }
function Info({ title, text }) { return <div><h3 className="font-bold">◉ {title}</h3><p className="mt-2 leading-relaxed text-[#777]">{text}</p></div> }
function SkillGroups({ language }) { const groups = language === 'en' ? [['Front-end', 'HTML', 'CSS', 'JavaScript', 'React'], ['Back-end', 'Java', 'Spring Boot', 'Node.js', 'C#'], ['Databases', 'PostgreSQL', 'MySQL', 'MongoDB'], ['Tools', 'Docker', 'Cloudflare', 'Git'], ['Other Technologies', 'GCP', 'BigQuery', 'Apps Script']] : [['Front-end', 'HTML', 'CSS', 'JavaScript', 'React'], ['Back-end', 'Java', 'Spring Boot', 'Node.js', 'C#'], ['Banco de Dados', 'PostgreSQL', 'MySQL', 'MongoDB'], ['Ferramentas', 'Docker', 'Cloudflare', 'Git'], ['Outras Tecnologias', 'GCP', 'BigQuery', 'Apps Script']]; return <div className="mt-5 grid gap-3 sm:grid-cols-3">{groups.map(([title, ...items]) => <div key={title} className="border border-[#e3e3e3] p-4"><strong className="text-xs">{title}</strong><div className="mt-3 flex flex-wrap gap-1">{items.map((item) => <span key={item} className="bg-[#f1f1f1] px-2 py-1 text-[10px] text-[#555]">{item}</span>)}</div></div>)}</div> }

export function AboutPage({ language }) { const t = labels[language]; const data = getContent(language); return <><Shell language={language} eyebrow={t.about} title={language === 'en' ? 'Get to know my journey' : 'Conheça minha trajetória'} description={language === 'en' ? 'Learn about my education, professional profile and the technologies in my path.' : 'Um pouco sobre minha formação, perfil profissional e as tecnologias que fazem parte do meu caminho.'}><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_0.8fr]"><div><h2 className="text-xl font-bold">{t.profile}</h2><p className="mt-5 text-sm leading-relaxed text-[#555]">{data.summary}</p><h2 className="mt-10 text-xl font-bold">{t.objective}</h2><p className="mt-5 text-sm leading-relaxed text-[#555]">{data.objective}</p></div><div className="border border-[#e3e3e3] bg-white p-6"><h2 className="text-xl font-bold">{language === 'en' ? 'Personal information' : 'Informações pessoais'}</h2><dl className="mt-6 grid gap-4 text-sm"><div><dt className="text-xs uppercase text-[#999]">{language === 'en' ? 'Nationality' : 'Nacionalidade'}</dt><dd className="mt-1">{language === 'en' ? 'Brazilian' : 'Brasileiro'}</dd></div><div><dt className="text-xs uppercase text-[#999]">{t.age}</dt><dd className="mt-1">20</dd></div><div><dt className="text-xs uppercase text-[#999]">{t.license}</dt><dd className="mt-1">{language === 'en' ? 'Category B' : 'Categoria B'}</dd></div></dl></div></div><h2 className="mt-14 text-xl font-bold">{t.skills}</h2><ul className="mt-5 flex flex-wrap gap-2" aria-label={t.skills}>{data.skills.map((skill) => <li key={skill} className="border border-[#ddd] bg-white px-3 py-2 text-xs">{skill}</li>)}</ul></Shell><Footer language={language} /></> }

export function ProjectsPage({ language }) { const t = labels[language]; const data = getContent(language); return <><Shell language={language} eyebrow={t.projects} title={t.projectsTitle} description={t.projectsDesc}><div className="mt-10 border-l border-[#ddd] pl-6">{data.projects.map((project, index) => <article key={project.title} className="relative mb-10"><span className={`absolute -left-[31px] top-1 h-3 w-3 rounded-full border-2 border-white ${index ? 'bg-[#ccc]' : 'bg-[#171717]'}`} /><div className="flex flex-wrap items-start justify-between gap-3"><h2 className="text-lg font-bold">{project.title}</h2><span className="bg-[#f1f1f1] px-2 py-1 text-[10px]">{t.project} {String(index + 1).padStart(2, '0')}</span></div><p className="mt-3 max-w-2xl text-xs leading-relaxed text-[#666]">{project.description}</p><div className="mt-3 flex gap-2">{project.tags.map((tag) => <span key={tag} className="border border-[#ddd] px-2 py-1 text-[10px]">#{tag}</span>)}</div><div className="mt-3 flex gap-2"><a href={project.url} target="_blank" rel="noreferrer" className="bg-[#171717] px-4 py-2 text-[10px] text-white">↗ {t.view}</a><a href={project.url} target="_blank" rel="noreferrer" className="border border-[#ddd] px-4 py-2 text-[10px]">⌘ {t.github}</a></div></article>)}</div></Shell><Footer language={language} /></> }

export function ExperiencePage({ language }) { const t = labels[language]; const data = getContent(language); return <><Shell language={language} eyebrow={t.experience} title={t.history} description={t.experienceDesc}><div className="mt-10 grid gap-7">{data.experience.map(([period, role, company, description]) => <article key={role} className="rounded-xl border border-[#ddd] p-6"><div className="flex flex-wrap-reverse items-start justify-between gap-3"><div><p className="text-[10px] uppercase text-[#888]">{t.exp}</p><h2 className="mt-2 text-lg font-bold">{company}</h2><p className="text-xs text-[#555]">{role}</p></div><span className="bg-[#171717] px-2 py-1 text-[10px] text-white">{period}</span></div><p className="mt-6 text-xs leading-relaxed text-[#666]">{description}</p></article>)}</div><div className="mt-16"><h2 className="text-xl font-bold">{t.academic}</h2><div className="mt-6 grid gap-5">{data.education.map(([period, course, institution]) => <article key={course} className="border-l-2 border-[#171717] pl-5"><p className="text-[10px] uppercase text-[#888]">{period}</p><h3 className="mt-2 text-sm font-bold">{course}</h3><p className="mt-1 text-xs text-[#777]">{institution}</p></article>)}</div></div></Shell><Footer language={language} /></> }

export function ContactPage({ language }) { const t = labels[language]; const data = getContent(language); return <><Shell language={language} eyebrow={t.contact} title={t.contact} description={t.contactDesc}><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_300px]"><div><h2 className="text-base font-bold">{t.contactInfo}</h2><div className="mt-6 grid gap-4">{[[t.email, data.email, `mailto:${data.email}`], [t.phone, data.phone, `tel:${data.phone.replace(/[^\d+]/g, '')}`], ['LinkedIn', 'linkedin.com/in/gabrielamaro2006', data.linkedin]].map(([label, value, href]) => <a key={label} href={href} target={label === 'LinkedIn' ? '_blank' : undefined} rel={label === 'LinkedIn' ? 'noreferrer' : undefined} className="flex items-center justify-between rounded-lg border border-[#eee] p-4 text-xs hover:border-[#aaa]"><span><small className="block text-[10px] uppercase text-[#999]">{label}</small><strong className="mt-1 block">{value}</strong></span><Arrow /></a>)}</div></div><form className="rounded-xl border border-[#ddd] p-5" onSubmit={(event) => handleContactSubmit(event, language)}><h2 className="text-base font-bold">{t.message}</h2><label className="mt-5 block text-[10px] font-bold">{t.name} <em className="font-normal text-[#999]">{t.required}</em><input name="name" required className="mt-2 block w-full rounded border border-[#ddd] px-3 py-2 text-xs font-normal outline-none focus:border-[#555]" placeholder={t.name} /></label><label className="mt-5 block text-[10px] font-bold">{t.email} <em className="font-normal text-[#999]">{t.required}</em><input name="email" type="email" required className="mt-2 block w-full rounded border border-[#ddd] px-3 py-2 text-xs font-normal outline-none focus:border-[#555]" placeholder={t.email} /></label><label className="mt-5 block text-[10px] font-bold">{t.messageField} <textarea name="message" required className="mt-2 block h-24 w-full resize-y rounded border border-[#ddd] px-3 py-2 text-xs font-normal outline-none focus:border-[#555]" placeholder={t.messageField} /></label><button type="submit" className="mt-5 w-full bg-[#171717] py-3 text-xs font-semibold text-white">{t.send} ↗</button></form></div></Shell><Footer language={language} /></> }
